### PR TITLE
Add open on new tab option

### PR DESCRIPTION
**Pull request by 3xbun**

### CODE REVIEW

**Comment by NellyWhads** [comment]
Hey there, having trouble actually reading the PR. Could kindly undo the formatting changes and only commit the code changes themselves. All files are currently formatted with 4-space indentation.

I will add a separate PR after we decide for/against this merge for consistent formatting.

Sorry - just can't figure out what the feature change is right now since a lot of lines have whitespace changes as well.

Cheers!

**Comment by NellyWhads** [comment]
@3xbun I still don't see the formatting changes being removed.

I think we can just default the behaviour to open in new tab so that the browsing experience isn't disturbed. This is the way links usually should behave when the user interaction will be a long running process (checking on download progress, choosing files, looking up alternate versions that may be available, etc.)

So let's just make this the default property and get rid of the extra context menu option that we'll have to add. I already don't like that there are 4 options added to the context menu - not very user friendly.

**Comment by 3xbun** [comment]
Yeah, agree. Let user decide in the first place. User rarely change it anyway. 
Working on new request now.

**Comment by NellyWhads** [comment]
Perfect - let's just append the property inline in the method for now.

I have some plans to update the `encode()` codepath, since users will probably use it when they are typing in a `textarea`, which currently doesn't work too well.

**Comment by NellyWhads** [comment]
Succeeded by #2 - Closing

**Pull request closed without merging**
